import { AIMessage, BaseMessage, HumanMessage } from '@langchain/core/messages';
import { JsonOutputParser, StringOutputParser } from '@langchain/core/output_parsers';
import { PromptTemplate } from '@langchain/core/prompts';
import { RunnableConfig } from '@langchain/core/runnables';
import { CompiledStateGraph, END, MemorySaver, START, StateGraph, StateGraphArgs } from '@langchain/langgraph';
import { ChatOpenAI } from '@langchain/openai';

/**
 * Use Case: Research Assistant for Topic Exploration (Orchestrator-Workers Pattern)
 *
 * This agent demonstrates the Orchestrator-Workers pattern. Given a research topic,
 * it dynamically breaks down the topic into sub-tasks (questions or areas to explore),
 * assigns each sub-task to a worker LLM for research/answering, and finally
 * synthesizes the results from all workers into a comprehensive report.
 *
 * Workflow:
 * 1. Input: Takes a research topic (e.g., "Explain the basics of Quantum Computing").
 * 2. Orchestrator Node: An LLM analyzes the input topic and generates a list of
 *    specific sub-tasks or questions needed to address the topic comprehensively.
 *    (e.g., ["Define qubit", "Explain superposition", "Explain entanglement", "List potential applications"]).
 * 3. Worker Nodes (Dynamic Parallel Execution): For each sub-task identified by the orchestrator,
 *    a separate worker LLM call is made (potentially in parallel) to research or answer
 *    that specific sub-task.
 * 4. Synthesizer Node: Collects all the answers/research findings from the worker nodes.
 *    Another LLM call synthesizes these findings into a single, coherent report addressing
 *    the original research topic.
 * 5. Output: The final synthesized report.
 *
 * This pattern is useful when the exact sub-steps required to complete a task are not
 * known beforehand and depend on the specific input. The orchestrator dynamically determines
 * the necessary work, and workers execute it.
 */

// --- State Definition ---
interface OrchestratorWorkerState {
    topic: string;
    sub_tasks: string[]; // List of tasks generated by the orchestrator
    worker_outputs: Record<string, string>; // Map of task -> result from workers
    final_report: string | null; // The final synthesized report
    messages: BaseMessage[]; // History for checkpointer
}

// --- Output Schemas ---
interface OrchestratorOutput {
    sub_tasks: string[];
}

// --- Graph Channels Definition ---
const agentStateChannels: StateGraphArgs<OrchestratorWorkerState>['channels'] = {
    topic: {
        value: (x?: string, y?: string) => y ?? x ?? '',
        default: () => '',
    },
    sub_tasks: {
        value: (x: string[], y: string[]) => y ?? x, // Overwrite with new tasks
        default: () => [],
    },
    // Use reducer for worker_outputs to merge results as they come in (though in this simple parallel model, they arrive together)
    worker_outputs: {
        value: (x: Record<string, string>, y: Record<string, string>) => ({ ...x, ...y }),
        default: () => ({}),
    },
    final_report: {
        value: (x: string | null, y: string | null) => y ?? x,
        default: () => null,
    },
    messages: {
        value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
        default: () => [],
    },
};

class OrchestratorWorkerAgent {
    private graph: StateGraph<OrchestratorWorkerState>;
    private compiledGraph: CompiledStateGraph<OrchestratorWorkerState, Partial<OrchestratorWorkerState>>;
    private checkpointer = new MemorySaver();
    private llm = new ChatOpenAI({ model: 'gpt-4.1', temperature: 0 });

    constructor() {
        this.graph = new StateGraph({ channels: agentStateChannels });

        // Define Nodes
        this.graph.addNode('orchestrator', this.orchestratorNode);
        this.graph.addNode('run_workers', this.runWorkersNode);
        this.graph.addNode('synthesizer', this.synthesizerNode);

        // Define Edges
        this.graph.addEdge(START, 'orchestrator' as any); // Use 'as any'
        this.graph.addEdge('orchestrator' as any, 'run_workers' as any); // Use 'as any'
        this.graph.addEdge('run_workers' as any, 'synthesizer' as any); // Use 'as any'
        this.graph.addEdge('synthesizer' as any, END); // Use 'as any'

        // Compile the graph
        this.compiledGraph = this.graph.compile({ checkpointer: this.checkpointer });
    }

    // --- Node Functions ---

    // Orchestrator: Breaks down the main topic into sub-tasks
    private orchestratorNode = async (state: OrchestratorWorkerState): Promise<Partial<OrchestratorWorkerState>> => {
        console.log('--- Orchestrator Node ---');
        const prompt = PromptTemplate.fromTemplate(
            `You are an expert research assistant. Given the following topic, break it down into a list of 3-5 specific sub-tasks or questions that need to be answered to provide a comprehensive overview.
            Respond with a JSON object containing a single key "sub_tasks" which is an array of strings.
            Example format: {{"sub_tasks": ["Question 1", "Question 2", "Area to research 3"]}}

            Topic: {topic}`,
        );
        const parser = new JsonOutputParser<OrchestratorOutput>();
        const chain = prompt.pipe(this.llm).pipe(parser);

        let sub_tasks: string[] = [];
        let aiMessageContent = '';
        try {
            const result = await chain.invoke({ topic: state.topic });
            sub_tasks = result.sub_tasks;
            aiMessageContent = `Identified sub-tasks: ${sub_tasks.join('; ')}`;
            console.log('Orchestrator identified tasks:', sub_tasks);
        } catch (error) {
            console.error('Orchestrator failed:', error);
            aiMessageContent = `Orchestrator failed to generate tasks: ${error}`;
            // Handle error - perhaps end the graph or retry? For now, return empty tasks.
            sub_tasks = [];
        }

        const humanMessage = new HumanMessage(`Break down topic: ${state.topic}`);
        const aiMessage = new AIMessage({ content: aiMessageContent });

        return { sub_tasks: sub_tasks, messages: [humanMessage, aiMessage] };
    };

    // Worker Logic (Helper function, not a graph node itself)
    private workerLogic = async (topic: string, task: string): Promise<string> => {
        console.log(`--- Worker executing task: ${task} ---`);
        const prompt = PromptTemplate.fromTemplate(
            `You are a research assistant. Provide a concise answer or summary for the following specific task, considering the overall topic.
            Overall Topic: {topic}
            Specific Task: {task}

            Provide only the answer/summary for the specific task.`,
        );
        const chain = prompt.pipe(this.llm).pipe(new StringOutputParser());
        try {
            const result = await chain.invoke({ topic: topic, task: task });
            console.log(`Worker result for "${task}":`, result.substring(0, 100) + '...'); // Log snippet
            return result;
        } catch (error) {
            console.error(`Worker failed for task "${task}":`, error);
            return `Error processing task: ${task}`;
        }
    };

    // Run Workers Node: Executes workerLogic for each sub_task in parallel
    private runWorkersNode = async (state: OrchestratorWorkerState): Promise<Partial<OrchestratorWorkerState>> => {
        console.log('--- Run Workers Node ---');
        const { topic, sub_tasks } = state;
        const worker_outputs: Record<string, string> = {};
        const promises: Promise<void>[] = [];
        const messages: BaseMessage[] = [new HumanMessage('Execute generated sub-tasks')];
    };

    // Synthesizer: Combines worker outputs into a final report
    private synthesizerNode = async (state: OrchestratorWorkerState): Promise<Partial<OrchestratorWorkerState>> => {
        console.log('--- Synthesizer Node ---');
        const { topic, worker_outputs } = state;
    };

    // --- Public Invocation Method ---

    async invoke(threadId: string, topic: string): Promise<Record<string, any>> {
        const initialState: OrchestratorWorkerState = {
            topic: topic,
            sub_tasks: [],
            worker_outputs: {},
            final_report: null,
            messages: [new HumanMessage(topic)], // Start with the user's topic
        };

        const config: RunnableConfig = { configurable: { thread_id: threadId } };
        let finalState: OrchestratorWorkerState | undefined;

        console.log(`--- Invoking Orchestrator-Worker Graph for Thread ${threadId} ---`);
        try {
            // Using invoke to get the final state directly
            finalState = (await this.compiledGraph.invoke(initialState, config)) as OrchestratorWorkerState; // Explicit cast

            if (finalState?.final_report) {
                console.log(`--- Invocation Complete for Thread ${threadId} ---`);
                return { final_report: finalState.final_report };
            } else {
                console.error(`--- Invocation Failed for Thread ${threadId}: No final report generated ---`);
                // Check intermediate states if needed from checkpointer or stream events
                const finalMessages = finalState?.messages ?? [];
                const lastMessage = finalMessages[finalMessages.length - 1]?.content ?? 'Unknown error state.';
                return { error: `An unexpected error occurred. Last known step: ${lastMessage}` };
            }
        } catch (error) {
            console.error(`--- Error Invoking Graph for Thread ${threadId}:`, error);
            return { error: `An error occurred while processing your request: ${error instanceof Error ? error.message : String(error)}` };
        }
    }

    async getState(threadId: string) {
        const config: RunnableConfig = { configurable: { thread_id: threadId } };
        try {
            const state = await this.checkpointer.get(config);
            return state;
        } catch (error) {
            console.error(`Error retrieving state for Thread ${threadId}:`, error);
            return null;
        }
    }
}

export const orchestratorWorkerAgent = new OrchestratorWorkerAgent();
